### ISSUE TITLE
Platform UNKNOWN in Lego device

### ISSUE THREAD

**Issue by adesito** [ev3dev-lang-java/installer#16]
Hi

I've a lego Brick device with ev3dev (kernel 4.4.87-22 last one I guess).
When I run installer.sh and download platform.sh, platform appears as UNKNOWN because in the if sentence it search lego-v3-battery but in my device the file is named as legov3-battery.

Regards.

**Comment by jabrena** [comment]
Good morning @adesito, maybe you downloaded installer from develop branch, but in last weeks, we are trying to migrate to EV3Dev Stretch and develop are using the latest features for that version. The stable version is Jessie. Can you use master branch to follow the procedure. In few weeks, we will have  the initial support for Debian Stretch with Java 9 installed in a automate way. But meanwhile, use the classic installation. Remember that you will have to move the Oracle JRE 8 to /home/robot continue with the process.

Cheers

**Comment by jabrena** [comment]
Tell me if you continue with problems.

Juan Antonio

**Comment by jabrena** [comment]
Related issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/464

I suppose that you fixed the problem.

For new doubts, it is better if you use this backlog:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues
