### ISSUE TITLE
Installer does not find jri-11-ev3

### ISSUE THREAD

**Issue by pluess** [ev3dev-lang-java/installer#36]
I did the recommended 

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo reboot

```

and then downloaded and starte the installer.sh to install java.

```
robot@ev3dev:~$ sudo ./installer.sh java

##############################
# EV3Dev-lang-java Installer #
##############################

Platform detected: ev3

No java detected
Installed Java version: '', installing anyway.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package jri-11-ev3
```

And not really a suprise:
```
robot@ev3dev:~$ sudo apt-get install jri-11-ev3
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package jri-11-ev3
```

So it looks that jri-11-ev3 is not a valid apt package name.

**Comment by jabrena** [comment]
Hi @pluess, 

Did you solve the issue?
What version are you using?

Juan Antonio

**Comment by JakubVanek** [comment]
Hmmm, the package is not uploaded for Jessie, that might have been the problem.

**Comment by jabrena** [comment]
Maybe for jessie, we could install java in the classic way, isnt it?

**Comment by JakubVanek** [comment]
I can upload the package to the repository, but I cannot guarantee that the java will work (and it is the same with unpackaged version) - we are building it on a new distro against new libraries.

**Comment by pluess** [comment]
I realized that I installed Jessie instead of Strech by mistake. 

As for as I understand Stretch is the correct verion forjava support on the EV3 Brick. So I will try again with Strech.

**Comment by jabrena** [comment]
Good morning @pluess.

if you use this image:
https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/2018-12-01/snapshot-ev3dev-stretch-ev3-generic-2018-11-30.img.xz

now Java is installed out of the box.

Merry Christmas!!!

Juan Antonio

**Comment by pluess** [comment]
Thanks. Installed the image and java -version gives:

```
robot@ev3dev:~$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-ev3)
OpenJDK Client VM (build 11.0.1+13-ev3, mixed mode, sharing)
```

However javac gives:
```
robot@ev3dev:~$ javac
-bash: javac: command not found
```

So how do I go about compiling projects? 

http://www.jev3dev.tk/getting_started-preparation.html tells me I need Maven. But the usual
`sudo apt-get install maven` doesn't work as well.

```
robot@ev3dev:~$ sudo apt-get install maven
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package maven
```

**Comment by JakubVanek** [comment]
Hi pluess,

we do not currently have a Debian package for full JDK on EV3. The JRI package is intentionally small - it is a subset of even the standard JRE.

I think the compilation will take a relatively long time on EV3. I recommend compiling java programs on PC. I also recommend using [template_project_gradle](https://github.com/ev3dev-lang-java/template-project-gradle/), as it is a part of the integration of Java to ev3dev. For example, it creates wrappers so you can run your programs directly from the EV3 menu. There is also a [Getting Started](https://github.com/ev3dev-lang-java/template-project-gradle/#getting-started) in there.

However, we do build the full JDK for EV3 plain archive, which you can download here: [jdk11_ev3/latest/jdk-ev3.tar.gz](https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk11_build_ev3_linux/lastSuccessfulBuild/artifact/build/jdk-ev3.tar.gz). You can unpack it somewhere and then replace the links installed in `/usr/bin` with links to the jdk directory.

Regards,

Jakub Vanek

**Comment by JakubVanek** [comment]
Hmmm, it seems that https://github.com/mob41/ev3dev-lang-java is a different project with a different API.
